services:
  postgres:
    image: postgres:16.0
    restart: always
    environment:
      TZ: America/Sao_Paulo
    env_file:
      - .env.docker
    ports:
      - "5433:5432"
    expose:
      - "5432"
    volumes:
      - pg-data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-agroecology-api
    restart: unless-stopped
    depends_on:
      - postgres
    env_file:
      - .env.docker
    ports:
      - "${PORT}:${PORT}"

volumes:
  pg-data:
    driver: local